### ISSUE TITLE
Can't install Sake ( git clone from GH version )

### ISSUE THREAD

**Issue by melezhik** [perlpilot/p6-sake#25]
Hi! I can't install Sake:

[root@cde86d46de7a p6-sake]# zef install . --force-install
===> Testing: sake
Warning: re-executing task “fred” per your request
===> Testing [OK] for sake
===> Installing: sake
===> Install [FAIL] for sake: ===SORRY!===
Could not find Sake::Task at line 1 in:
    /opt/rakudo-pkg/share/perl6/site
    /opt/rakudo-pkg/share/perl6/vendor
    /opt/rakudo-pkg/share/perl6
    CompUnit::Repository::AbsolutePath<63251904>
    CompUnit::Repository::NQP<41782416>
    CompUnit::Repository::Perl5<41782456>

===SORRY!===
Could not find Sake::Task at line 1 in:
    /opt/rakudo-pkg/share/perl6/site
    /opt/rakudo-pkg/share/perl6/vendor
    /opt/rakudo-pkg/share/perl6
    CompUnit::Repository::AbsolutePath<63251904>
    CompUnit::Repository::NQP<41782416>
    CompUnit::Repository::Perl5<41782456>

**Comment by AlexDaniel** [comment]
Ahh, it's my mistake! Will fix shortly!

**Comment by AlexDaniel** [comment]
What about now? https://github.com/perl6/p6-sake/commit/08ce6c0628cd3332af726043c955b175d7b4b24a

**Comment by melezhik** [comment]
looks good now. thanks

[root@cde86d46de7a p6-sake]# zef install . --force-install
===> Testing: sake
Warning: re-executing task “fred” per your request
===> Testing [OK] for sake
===> Installing: sake

1 bin/ script [sake] installed to:
/opt/rakudo-pkg/share/perl6/site/bin

**Comment by AlexDaniel** [comment]
Cool, thanks for checking! I pushed some major changes lately, so please let me know if you see any other problems.
