### ISSUE TITLE
`ake` not found

### ISSUE THREAD

**Issue by JJ** [perlpilot/p6-sake#32]
After installing using zef, and apparently installing correctly two scripts, `ake` seems not to be found in the PATH, while sake is.

**Comment by JJ** [comment]
It looks like it's not really installed in the /bin directory, unlike `ake`. Maybe some version impedance?

**Comment by AlexDaniel** [comment]
[Bumped](https://github.com/Raku/ake/commit/c5020ee5609c610adf7a0ddc6cf0540abecd59cd). It'll probably take a little bit of time for things to catch up, but maybe try again tomorrow and see if it works.

**Comment by JJ** [comment]
Thanks!
